backend:
  name: github
  repo: kevindiska/kevins_site
  branch: main
  #  auth_endpoint: /auth
  base_url: "https://kevinverse.duckdns.org/"

# ✅ Commit messages for CMS actions
commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
  openAuthoring: '{{message}}'

# ✅ Define where uploaded images go
media_folder: "static/uploads"
public_folder: "/uploads"

# ✅ Required: Media Library
media_library:
  name: uploadcare
  config:
    publicKey: demo  # Change this to your Uploadcare public key if needed

# Editor preview so its fancy
editor:
  preview: true
  preview_styles: "/assets/css/stylesheet.45e028aa8ce0961349adf411b013ee39406be2c0bc80d4ea3fc04555f7f4611a.css" # Adjust the path to your PaperMod CSS file


# ✅ Collections (Defines how CMS handles content)
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Author", name: "author", widget: "string", default: "Kevin" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
